import { DocumentItem, User, WorkflowTemplate, NotificationItem, DepartmentItem, JobTitleItem } from '../types';
import { ROLE_PRESET_PERMISSIONS } from './permissions';

export const USERS: User[] = [
  {
    id: 'user-long',
    name: 'Nguyễn Văn Long',
    username: 'long.nv',
    pass: '123456',
    email: 'long.nv@trunghai.com.vn',
    role: 'STAFF',
    roleTitle: 'Chuyên viên Dự án & Hợp đồng',
    department: 'Phòng Kỹ thuật & Dự án',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    permissions: [...ROLE_PRESET_PERMISSIONS.STAFF]
  },
  {
    id: 'user-mai',
    name: 'Trần Thị Mai',
    username: 'mai.tt',
    pass: '123456',
    email: 'mai.tt@trunghai.com.vn',
    role: 'DEPT_HEAD',
    roleTitle: 'Trưởng phòng Kỹ thuật & Dự án',
    department: 'Phòng Kỹ thuật & Dự án',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    permissions: [...ROLE_PRESET_PERMISSIONS.DEPT_HEAD]
  },
  {
    id: 'user-nam',
    name: 'Phạm Hoàng Nam',
    username: 'nam.ph',
    pass: '123456',
    email: 'nam.ph@trunghai.com.vn',
    role: 'CHIEF_ACCOUNTANT',
    roleTitle: 'Kế toán trưởng',
    department: 'Phòng Tài chính Kế toán',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    permissions: [...ROLE_PRESET_PERMISSIONS.CHIEF_ACCOUNTANT]
  },
  {
    id: 'user-tuan',
    name: 'Đặng Minh Tuấn',
    username: 'tuan.dm',
    pass: '123456',
    email: 'tuan.dm@trunghai.com.vn',
    role: 'LEGAL_DEPT',
    roleTitle: 'Trưởng bộ phận Pháp chế',
    department: 'Ban Pháp chế & Kiểm soát',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    permissions: [...ROLE_PRESET_PERMISSIONS.LEGAL_DEPT]
  },
  {
    id: 'user-hai',
    name: 'Đỗ Trung Hải',
    username: 'hai.dt',
    pass: '123456',
    email: 'hai.dt@trunghai.com.vn',
    role: 'DIRECTOR',
    roleTitle: 'Tổng Giám đốc',
    department: 'Ban Giám đốc',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    permissions: [...ROLE_PRESET_PERMISSIONS.DIRECTOR]
  },
  {
    id: 'user-khai',
    name: 'Hoàng Văn Khải',
    username: 'khai.hv',
    pass: '123456',
    email: 'khai.hv@trunghai.com.vn',
    role: 'DEPT_HEAD',
    roleTitle: 'Phó Trưởng phòng Kỹ thuật & Dự án',
    department: 'Phòng Kỹ thuật & Dự án',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    permissions: [...ROLE_PRESET_PERMISSIONS.DEPT_HEAD],
    secondaryPositions: [
      {
        roleTitle: 'Trưởng phòng Cung ứng & Vật tư',
        department: 'Phòng Cung ứng & Vật tư',
        role: 'DEPT_HEAD'
      }
    ]
  },
  {
    id: 'user-admin',
    name: 'Quản Trị Viên',
    username: 'admin',
    pass: 'admin123',
    email: 'admin@trunghai.com.vn',
    role: 'ADMIN',
    roleTitle: 'Quản trị viên Hệ thống',
    department: 'Phòng CNTT & Hạ tầng',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    permissions: [...ROLE_PRESET_PERMISSIONS.ADMIN]
  }
];

export const WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'wf-contract-major',
    name: 'Quy trình Trình ký Hợp đồng Kinh tế (> 100 Triệu)',
    category: 'Hợp đồng kinh tế',
    description: 'Áp dụng cho mọi hợp đồng mua sắm vật tư, thiết bị, gói thầu có giá trị trên 100.000.000 VNĐ',
    steps: [
      { order: 1, title: 'Kiểm tra kỹ thuật & phạm vi', role: 'DEPT_HEAD', roleTitle: 'Trưởng phòng Dự án', department: 'Phòng Kỹ thuật & Dự án', slaHours: 8 },
      { order: 2, title: 'Thẩm định điều khoản pháp lý & Rủi ro', role: 'LEGAL_DEPT', roleTitle: 'Pháp chế', department: 'Ban Pháp chế & Kiểm soát', slaHours: 12 },
      { order: 3, title: 'Kiểm soát ngân sách & Điều khoản thanh toán', role: 'CHIEF_ACCOUNTANT', roleTitle: 'Kế toán trưởng', department: 'Phòng Tài chính Kế toán', slaHours: 8 },
      { order: 4, title: 'Phê duyệt & Ký số Hợp đồng', role: 'DIRECTOR', roleTitle: 'Tổng Giám đốc', department: 'Ban Giám đốc', slaHours: 24 },
    ]
  },
  {
    id: 'wf-proposal-budget',
    name: 'Quy trình Phê duyệt Tờ trình & Dự toán Chi phí',
    category: 'Tờ trình phê duyệt',
    description: 'Dành cho tờ trình mua sắm nội bộ, chi phí công tác, nâng cấp hạ tầng',
    steps: [
      { order: 1, title: 'Xác nhận sự cần thiết & Kế hoạch', role: 'DEPT_HEAD', roleTitle: 'Trưởng phòng Bộ phận', department: 'Phòng ban đề xuất', slaHours: 8 },
      { order: 2, title: 'Thẩm định định mức chi & Nguồn vốn', role: 'CHIEF_ACCOUNTANT', roleTitle: 'Kế toán trưởng', department: 'Phòng Tài chính Kế toán', slaHours: 8 },
      { order: 3, title: 'Phê duyệt hạn mức thực hiện', role: 'DIRECTOR', roleTitle: 'Tổng Giám đốc', department: 'Ban Giám đốc', slaHours: 16 },
    ]
  },
  {
    id: 'wf-payment-request',
    name: 'Quy trình Đề xuất & Ủy nhiệm Thanh toán',
    category: 'Hồ sơ thanh toán',
    description: 'Thanh toán tiền hàng nhà cung cấp, tạm ứng hợp đồng, hoàn ứng công tác',
    steps: [
      { order: 1, title: 'Đối soát khối lượng nghiệm thu', role: 'DEPT_HEAD', roleTitle: 'Trưởng phòng Dự án', department: 'Phòng Kỹ thuật & Dự án', slaHours: 4 },
      { order: 2, title: 'Kiểm tra hóa đơn chứng từ hợp lệ', role: 'CHIEF_ACCOUNTANT', roleTitle: 'Kế toán trưởng', department: 'Phòng Tài chính Kế toán', slaHours: 4 },
      { order: 3, title: 'Duyệt chi chuyển khoản / Tiền mặt', role: 'DIRECTOR', roleTitle: 'Tổng Giám đốc', department: 'Ban Giám đốc', slaHours: 8 },
    ]
  }
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-001',
    code: 'HĐ-2026/TH-048',
    title: 'Hợp đồng cung cấp & tích hợp hệ thống tự động hóa Scada - Gói thầu Xi măng Nghi Sơn',
    category: 'Hợp đồng kinh tế',
    department: 'Phòng Kỹ thuật & Dự án',
    creatorId: 'user-long',
    creatorName: 'Nguyễn Văn Long',
    creatorTitle: 'Chuyên viên Dự án & Hợp đồng',
    createdAt: '2026-09-17T09:30:00+07:00',
    updatedAt: '2026-09-18T14:15:00+07:00',
    deadline: '2026-09-20T17:00:00+07:00',
    priority: 'VERY_URGENT',
    status: 'IN_PROGRESS',
    amount: 1450000000,
    description: 'Kính trình Ban Giám đốc và các phòng ban xem xét phê duyệt hợp đồng mua sắm thiết bị PLC, cảm biến nhiệt và phần mềm tích hợp điều khiển trung tâm cho dự án nâng cấp dây chuyền nghiền 2.',
    currentStepIndex: 2,
    attachments: [
      {
        id: 'att-101',
        name: 'Hop_dong_cung_cap_thiet_bi_Nghi_Son_2026.pdf',
        size: 3450000,
        type: 'application/pdf',
        url: '#',
        uploadedAt: '2026-09-17T09:30:00+07:00',
        uploadedBy: 'Nguyễn Văn Long',
        isScan: true,
      },
      {
        id: 'att-102',
        name: 'Bang_chao_gia_va_thong_so_ky_thuat_kem_theo.xlsx',
        size: 1120000,
        type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        url: '#',
        uploadedAt: '2026-09-17T09:32:00+07:00',
        uploadedBy: 'Nguyễn Văn Long',
      },
      {
        id: 'att-103',
        name: 'Ban_scan_Giay_uy_quyen_ky_hop_dong_Doi_tac.pdf',
        size: 890000,
        type: 'application/pdf',
        url: '#',
        uploadedAt: '2026-09-17T09:35:00+07:00',
        uploadedBy: 'Nguyễn Văn Long',
        isScan: true,
      }
    ],
    steps: [
      {
        id: 'step-1',
        stepOrder: 1,
        title: 'Kiểm tra kỹ thuật & phạm vi',
        approverRole: 'DEPT_HEAD',
        approverId: 'user-mai',
        approverName: 'Trần Thị Mai',
        approverTitle: 'Trưởng phòng Kỹ thuật & Dự án',
        department: 'Phòng Kỹ thuật & Dự án',
        status: 'APPROVED',
        comment: 'Đã rà soát kỹ bảng thông số kỹ thuật và tiến độ bàn giao 45 ngày, đáp ứng yêu cầu kỹ thuật chủ đầu tư.',
        decisionDate: '2026-09-17T14:20:00+07:00',
        signatureImage: 'signature_mai',
        slaHours: 8,
      },
      {
        id: 'step-2',
        stepOrder: 2,
        title: 'Thẩm định điều khoản pháp lý & Rủi ro',
        approverRole: 'LEGAL_DEPT',
        approverId: 'user-tuan',
        approverName: 'Đặng Minh Tuấn',
        approverTitle: 'Trưởng bộ phận Pháp chế',
        department: 'Ban Pháp chế & Kiểm soát',
        status: 'APPROVED',
        comment: 'Điều khoản bảo hành 24 tháng và bảo lãnh hợp đồng 5% đã được đối tác đồng ý theo đúng form chuẩn.',
        decisionDate: '2026-09-18T10:05:00+07:00',
        signatureImage: 'signature_tuan',
        slaHours: 12,
      },
      {
        id: 'step-3',
        stepOrder: 3,
        title: 'Kiểm soát ngân sách & Điều khoản thanh toán',
        approverRole: 'CHIEF_ACCOUNTANT',
        approverId: 'user-nam',
        approverName: 'Phạm Hoàng Nam',
        approverTitle: 'Kế toán trưởng',
        department: 'Phòng Tài chính Kế toán',
        status: 'CURRENT',
        slaHours: 8,
      },
      {
        id: 'step-4',
        stepOrder: 4,
        title: 'Phê duyệt & Ký số Hợp đồng',
        approverRole: 'DIRECTOR',
        approverId: 'user-hai',
        approverName: 'Đỗ Trung Hải',
        approverTitle: 'Tổng Giám đốc',
        department: 'Ban Giám đốc',
        status: 'PENDING',
        slaHours: 24,
      }
    ],
    auditLogs: [
      {
        id: 'log-1',
        documentId: 'doc-001',
        action: 'CREATE',
        actorId: 'user-long',
        actorName: 'Nguyễn Văn Long',
        actorTitle: 'Chuyên viên Dự án',
        timestamp: '2026-09-17T09:30:00+07:00',
        comment: 'Tạo mới hồ sơ trình ký hợp đồng Nghi Sơn',
        newStatus: 'PENDING',
      },
      {
        id: 'log-2',
        documentId: 'doc-001',
        action: 'APPROVE',
        actorId: 'user-mai',
        actorName: 'Trần Thị Mai',
        actorTitle: 'Trưởng phòng Kỹ thuật',
        timestamp: '2026-09-17T14:20:00+07:00',
        comment: 'Đã duyệt bước 1 (Kỹ thuật)',
        previousStatus: 'PENDING',
        newStatus: 'IN_PROGRESS',
      },
      {
        id: 'log-3',
        documentId: 'doc-001',
        action: 'APPROVE',
        actorId: 'user-tuan',
        actorName: 'Đặng Minh Tuấn',
        actorTitle: 'Trưởng BP Pháp chế',
        timestamp: '2026-09-18T10:05:00+07:00',
        comment: 'Đã duyệt bước 2 (Pháp chế)',
        previousStatus: 'IN_PROGRESS',
        newStatus: 'IN_PROGRESS',
      }
    ]
  },
  {
    id: 'doc-002',
    code: 'TTr-2026/TH-112',
    title: 'Tờ trình đề xuất phê duyệt kinh phí bảo dưỡng định kỳ hệ thống máy chủ & nâng cấp Firewall Quý 3/2026',
    category: 'Tờ trình phê duyệt',
    department: 'Phòng CNTT & Hạ tầng',
    creatorId: 'user-long',
    creatorName: 'Nguyễn Văn Long',
    creatorTitle: 'Chuyên viên Quản trị Hệ thống',
    createdAt: '2026-09-18T08:15:00+07:00',
    updatedAt: '2026-09-18T11:45:00+07:00',
    deadline: '2026-09-22T17:00:00+07:00',
    priority: 'URGENT',
    status: 'IN_PROGRESS',
    amount: 86500000,
    description: 'Nhằm đảm bảo hệ thống vận hành liên tục 24/7 và gia hạn bản quyền FortiGate trước ngày 30/09/2026, phòng CNTT kính trình phê duyệt gói bảo dưỡng định kỳ.',
    currentStepIndex: 2,
    attachments: [
      {
        id: 'att-201',
        name: 'To_trinh_bao_duong_ha_tang_Q3_2026.pdf',
        size: 1420000,
        type: 'application/pdf',
        url: '#',
        uploadedAt: '2026-09-18T08:15:00+07:00',
        uploadedBy: 'Nguyễn Văn Long',
        isScan: true,
      },
      {
        id: 'att-202',
        name: 'Bao_gia_3_don_vi_cung_cap_dich_vu.pdf',
        size: 2150000,
        type: 'application/pdf',
        url: '#',
        uploadedAt: '2026-09-18T08:18:00+07:00',
        uploadedBy: 'Nguyễn Văn Long',
      }
    ],
    steps: [
      {
        id: 'step-201',
        stepOrder: 1,
        title: 'Xác nhận nhu cầu thiết yếu',
        approverRole: 'DEPT_HEAD',
        approverId: 'user-mai',
        approverName: 'Trần Thị Mai',
        approverTitle: 'Trưởng phòng Kỹ thuật & CNTT',
        department: 'Phòng Kỹ thuật & Dự án',
        status: 'APPROVED',
        comment: 'Đồng ý tờ trình, chi phí nằm trong định mức kế hoạch năm của phòng.',
        decisionDate: '2026-09-18T09:30:00+07:00',
        signatureImage: 'signature_mai',
        slaHours: 8,
      },
      {
        id: 'step-202',
        stepOrder: 2,
        title: 'Thẩm định định mức chi & Nguồn vốn',
        approverRole: 'CHIEF_ACCOUNTANT',
        approverId: 'user-nam',
        approverName: 'Phạm Hoàng Nam',
        approverTitle: 'Kế toán trưởng',
        department: 'Phòng Tài chính Kế toán',
        status: 'APPROVED',
        comment: 'Đã kiểm tra nguồn kinh phí thường xuyên Quý 3 còn dư đủ chi trả.',
        decisionDate: '2026-09-18T11:45:00+07:00',
        signatureImage: 'signature_nam',
        slaHours: 8,
      },
      {
        id: 'step-203',
        stepOrder: 3,
        title: 'Phê duyệt hạn mức thực hiện',
        approverRole: 'DIRECTOR',
        approverId: 'user-hai',
        approverName: 'Đỗ Trung Hải',
        approverTitle: 'Tổng Giám đốc',
        department: 'Ban Giám đốc',
        status: 'CURRENT',
        slaHours: 16,
      }
    ],
    auditLogs: [
      {
        id: 'log-201',
        documentId: 'doc-002',
        action: 'CREATE',
        actorId: 'user-long',
        actorName: 'Nguyễn Văn Long',
        actorTitle: 'Chuyên viên CNTT',
        timestamp: '2026-09-18T08:15:00+07:00',
        comment: 'Trình tờ trình bảo dưỡng máy chủ Q3',
        newStatus: 'PENDING',
      },
      {
        id: 'log-202',
        documentId: 'doc-002',
        action: 'APPROVE',
        actorId: 'user-mai',
        actorName: 'Trần Thị Mai',
        actorTitle: 'Trưởng phòng',
        timestamp: '2026-09-18T09:30:00+07:00',
        comment: 'Duyệt bước 1',
        previousStatus: 'PENDING',
        newStatus: 'IN_PROGRESS',
      },
      {
        id: 'log-203',
        documentId: 'doc-002',
        action: 'APPROVE',
        actorId: 'user-nam',
        actorName: 'Phạm Hoàng Nam',
        actorTitle: 'Kế toán trưởng',
        timestamp: '2026-09-18T11:45:00+07:00',
        comment: 'Duyệt bước 2',
        previousStatus: 'IN_PROGRESS',
        newStatus: 'IN_PROGRESS',
      }
    ]
  },
  {
    id: 'doc-003',
    code: 'BB-2026/TH-025',
    title: 'Biên bản nghiệm thu hoàn thành giai đoạn 1 & Đề nghị thanh toán Đợt 2 - Dự án Scada Tân Cảng',
    category: 'Hồ sơ thanh toán',
    department: 'Phòng Kỹ thuật & Dự án',
    creatorId: 'user-long',
    creatorName: 'Nguyễn Văn Long',
    creatorTitle: 'Chuyên viên Quản lý Hợp đồng',
    createdAt: '2026-09-14T10:00:00+07:00',
    updatedAt: '2026-09-16T16:30:00+07:00',
    deadline: '2026-09-17T17:00:00+07:00',
    priority: 'NORMAL',
    status: 'APPROVED',
    amount: 620000000,
    description: 'Hồ sơ đã bao gồm biên bản bàn giao thiết bị tại công trường, hóa đơn VAT điện tử và xác nhận của đại diện giám sát Tân Cảng.',
    currentStepIndex: 3,
    signedPdfUrl: '#',
    attachments: [
      {
        id: 'att-301',
        name: 'Bien_ban_nghiem_thu_Tan_Cang_GD1_scan_da_ky.pdf',
        size: 4200000,
        type: 'application/pdf',
        url: '#',
        uploadedAt: '2026-09-14T10:00:00+07:00',
        uploadedBy: 'Nguyễn Văn Long',
        isScan: true,
      },
      {
        id: 'att-302',
        name: 'De_nghi_thanh_toan_dot_2_hoa_don_vat.pdf',
        size: 1800000,
        type: 'application/pdf',
        url: '#',
        uploadedAt: '2026-09-14T10:05:00+07:00',
        uploadedBy: 'Nguyễn Văn Long',
        isScan: true,
      }
    ],
    steps: [
      {
        id: 'step-301',
        stepOrder: 1,
        title: 'Đối soát khối lượng nghiệm thu',
        approverRole: 'DEPT_HEAD',
        approverId: 'user-mai',
        approverName: 'Trần Thị Mai',
        approverTitle: 'Trưởng phòng Kỹ thuật',
        department: 'Phòng Kỹ thuật & Dự án',
        status: 'APPROVED',
        comment: 'Khối lượng thiết bị đã giao đủ 100% theo hợp đồng số 18/2026.',
        decisionDate: '2026-09-15T09:00:00+07:00',
        signatureImage: 'signature_mai',
        slaHours: 4,
      },
      {
        id: 'step-302',
        stepOrder: 2,
        title: 'Kiểm tra hóa đơn chứng từ hợp lệ',
        approverRole: 'CHIEF_ACCOUNTANT',
        approverId: 'user-nam',
        approverName: 'Phạm Hoàng Nam',
        approverTitle: 'Kế toán trưởng',
        department: 'Phòng Tài chính Kế toán',
        status: 'APPROVED',
        comment: 'Hóa đơn điện tử hợp lệ, đã trừ số tiền tạm ứng 20% đợt 1.',
        decisionDate: '2026-09-15T15:20:00+07:00',
        signatureImage: 'signature_nam',
        slaHours: 4,
      },
      {
        id: 'step-303',
        stepOrder: 3,
        title: 'Duyệt chi chuyển khoản / Tiền mặt',
        approverRole: 'DIRECTOR',
        approverId: 'user-hai',
        approverName: 'Đỗ Trung Hải',
        approverTitle: 'Tổng Giám đốc',
        department: 'Ban Giám đốc',
        status: 'APPROVED',
        comment: 'Phê duyệt chi chuyển khoản đợt 2 theo đề xuất của Kế toán trưởng.',
        decisionDate: '2026-09-16T16:30:00+07:00',
        signatureImage: 'signature_hai',
        slaHours: 8,
      }
    ],
    auditLogs: [
      {
        id: 'log-301',
        documentId: 'doc-003',
        action: 'CREATE',
        actorId: 'user-long',
        actorName: 'Nguyễn Văn Long',
        actorTitle: 'Chuyên viên Hợp đồng',
        timestamp: '2026-09-14T10:00:00+07:00',
        newStatus: 'PENDING',
      },
      {
        id: 'log-302',
        documentId: 'doc-003',
        action: 'APPROVE',
        actorId: 'user-hai',
        actorName: 'Đỗ Trung Hải',
        actorTitle: 'Tổng Giám đốc',
        timestamp: '2026-09-16T16:30:00+07:00',
        comment: 'Đã hoàn tất ký số và đóng dấu điện tử phê duyệt',
        previousStatus: 'IN_PROGRESS',
        newStatus: 'APPROVED',
      }
    ]
  },
  {
    id: 'doc-004',
    code: 'HĐ-2026/TH-051',
    title: 'Hợp đồng nguyên tắc mua sắm linh kiện điện tử chuyên dụng từ Công ty TNHH Mitsuoka Electric',
    category: 'Hợp đồng kinh tế',
    department: 'Phòng Cung ứng & Vật tư',
    creatorId: 'user-long',
    creatorName: 'Nguyễn Văn Long',
    creatorTitle: 'Chuyên viên Mua hàng',
    createdAt: '2026-09-16T14:00:00+07:00',
    updatedAt: '2026-09-17T11:20:00+07:00',
    deadline: '2026-09-19T17:00:00+07:00',
    priority: 'NORMAL',
    status: 'ADDITIONAL_REQ',
    amount: 320000000,
    description: 'Trình ký hợp đồng nguyên tắc thời hạn 1 năm với đối tác Mitsuoka để giữ mức chiết khấu 8.5% cho tất cả các đơn hàng linh kiện phụ trợ.',
    currentStepIndex: 1,
    attachments: [
      {
        id: 'att-401',
        name: 'Du_thao_HD_Nguyen_tac_Mitsuoka_2026.docx',
        size: 980000,
        type: 'application/docx',
        url: '#',
        uploadedAt: '2026-09-16T14:00:00+07:00',
        uploadedBy: 'Nguyễn Văn Long',
      }
    ],
    steps: [
      {
        id: 'step-401',
        stepOrder: 1,
        title: 'Kiểm tra kỹ thuật & giá',
        approverRole: 'DEPT_HEAD',
        approverId: 'user-mai',
        approverName: 'Trần Thị Mai',
        approverTitle: 'Trưởng phòng',
        department: 'Phòng Kỹ thuật & Dự án',
        status: 'APPROVED',
        comment: 'Danh mục vật tư phù hợp kế hoạch sản xuất năm 2026.',
        decisionDate: '2026-09-16T16:00:00+07:00',
        slaHours: 8,
      },
      {
        id: 'step-402',
        stepOrder: 2,
        title: 'Thẩm định điều khoản pháp lý',
        approverRole: 'LEGAL_DEPT',
        approverId: 'user-tuan',
        approverName: 'Đặng Minh Tuấn',
        approverTitle: 'Pháp chế',
        department: 'Ban Pháp chế & Kiểm soát',
        status: 'REJECTED',
        comment: 'Đề nghị bổ sung phụ lục danh mục đơn giá cam kết cố định 6 tháng và điều khoản phạt vi phạm giao hàng chậm.',
        decisionDate: '2026-09-17T11:20:00+07:00',
        slaHours: 12,
      },
      {
        id: 'step-403',
        stepOrder: 3,
        title: 'Kiểm soát ngân sách',
        approverRole: 'CHIEF_ACCOUNTANT',
        approverId: 'user-nam',
        approverName: 'Phạm Hoàng Nam',
        approverTitle: 'Kế toán trưởng',
        department: 'Phòng Tài chính Kế toán',
        status: 'PENDING',
        slaHours: 8,
      },
      {
        id: 'step-404',
        stepOrder: 4,
        title: 'Tổng Giám đốc ký duyệt',
        approverRole: 'DIRECTOR',
        approverId: 'user-hai',
        approverName: 'Đỗ Trung Hải',
        approverTitle: 'Tổng Giám đốc',
        department: 'Ban Giám đốc',
        status: 'PENDING',
        slaHours: 24,
      }
    ],
    auditLogs: [
      {
        id: 'log-401',
        documentId: 'doc-004',
        action: 'CREATE',
        actorId: 'user-long',
        actorName: 'Nguyễn Văn Long',
        actorTitle: 'Chuyên viên',
        timestamp: '2026-09-16T14:00:00+07:00',
        newStatus: 'PENDING',
      },
      {
        id: 'log-402',
        documentId: 'doc-004',
        action: 'REQUEST_INFO',
        actorId: 'user-tuan',
        actorName: 'Đặng Minh Tuấn',
        actorTitle: 'Pháp chế',
        timestamp: '2026-09-17T11:20:00+07:00',
        comment: 'Yêu cầu bổ sung phụ lục đơn giá và điều khoản phạt',
        previousStatus: 'IN_PROGRESS',
        newStatus: 'ADDITIONAL_REQ',
      }
    ]
  },
  {
    id: 'doc-005',
    code: 'TTr-2026/TH-119',
    title: 'Tờ trình đề xuất cử đoàn cán bộ kỹ thuật tham gia Hội chợ Công nghệ Năng lượng Tái tạo tại Singapore',
    category: 'Tờ trình phê duyệt',
    department: 'Phòng Kỹ thuật & Dự án',
    creatorId: 'user-long',
    creatorName: 'Nguyễn Văn Long',
    creatorTitle: 'Chuyên viên Dự án',
    createdAt: '2026-09-18T14:00:00+07:00',
    updatedAt: '2026-09-18T14:00:00+07:00',
    deadline: '2026-09-21T17:00:00+07:00',
    priority: 'NORMAL',
    status: 'PENDING',
    amount: 125000000,
    description: 'Đề xuất cử 03 kỹ sư chủ chốt tham dự hội thảo và xúc tiến gặp gỡ các nhà cung cấp giải pháp lưu trữ năng lượng pin Lithium BESS.',
    currentStepIndex: 0,
    attachments: [
      {
        id: 'att-501',
        name: 'To_trinh_va_chuong_trinh_hoi_thao_Singapore.pdf',
        size: 1950000,
        type: 'application/pdf',
        url: '#',
        uploadedAt: '2026-09-18T14:00:00+07:00',
        uploadedBy: 'Nguyễn Văn Long',
        isScan: true,
      },
      {
        id: 'att-502',
        name: 'Du_toan_chi_phi_ve_may_bay_khach_san.xlsx',
        size: 450000,
        type: 'application/xlsx',
        url: '#',
        uploadedAt: '2026-09-18T14:05:00+07:00',
        uploadedBy: 'Nguyễn Văn Long',
      }
    ],
    steps: [
      {
        id: 'step-501',
        stepOrder: 1,
        title: 'Xác nhận nhân sự & lịch trình',
        approverRole: 'DEPT_HEAD',
        approverId: 'user-mai',
        approverName: 'Trần Thị Mai',
        approverTitle: 'Trưởng phòng Kỹ thuật',
        department: 'Phòng Kỹ thuật & Dự án',
        status: 'CURRENT',
        slaHours: 8,
      },
      {
        id: 'step-502',
        stepOrder: 2,
        title: 'Thẩm định chi phí công tác nước ngoài',
        approverRole: 'CHIEF_ACCOUNTANT',
        approverId: 'user-nam',
        approverName: 'Phạm Hoàng Nam',
        approverTitle: 'Kế toán trưởng',
        department: 'Phòng Tài chính Kế toán',
        status: 'PENDING',
        slaHours: 8,
      },
      {
        id: 'step-503',
        stepOrder: 3,
        title: 'Tổng Giám đốc phê duyệt',
        approverRole: 'DIRECTOR',
        approverId: 'user-hai',
        approverName: 'Đỗ Trung Hải',
        approverTitle: 'Tổng Giám đốc',
        department: 'Ban Giám đốc',
        status: 'PENDING',
        slaHours: 16,
      }
    ],
    auditLogs: [
      {
        id: 'log-501',
        documentId: 'doc-005',
        action: 'CREATE',
        actorId: 'user-long',
        actorName: 'Nguyễn Văn Long',
        actorTitle: 'Chuyên viên',
        timestamp: '2026-09-18T14:00:00+07:00',
        comment: 'Tạo tờ trình cử đoàn công tác Singapore',
        newStatus: 'PENDING',
      }
    ]
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Hồ sơ mới cần duyệt',
    message: 'Bạn có hồ sơ "HĐ-2026/TH-048" đang chờ ký duyệt tại bước 3 (Kế toán trưởng).',
    documentId: 'doc-001',
    documentCode: 'HĐ-2026/TH-048',
    type: 'ACTION_REQUIRED',
    read: false,
    createdAt: '2026-09-18T10:05:00+07:00',
    actorId: 'user-tuan',
    recipientId: 'user-nam',
    recipientRole: 'CHIEF_ACCOUNTANT',
    targetStepIndex: 2,
    targetDepartment: 'Phòng Tài chính Kế toán',
  },
  {
    id: 'notif-2',
    title: 'Hồ sơ đã được phê duyệt',
    message: 'Hồ sơ "BB-2026/TH-025 - Dự án Tân Cảng" đã được Tổng Giám đốc hoàn tất phê duyệt & ký số.',
    documentId: 'doc-003',
    documentCode: 'BB-2026/TH-025',
    type: 'APPROVED',
    read: false,
    createdAt: '2026-09-16T16:30:00+07:00',
    actorId: 'user-hai',
    recipientId: 'user-tuan',
  },
  {
    id: 'notif-3',
    title: 'Yêu cầu bổ sung hồ sơ',
    message: 'Phòng Pháp chế yêu cầu bổ sung phụ lục đối với hồ sơ "HĐ-2026/TH-051".',
    documentId: 'doc-004',
    documentCode: 'HĐ-2026/TH-051',
    type: 'REJECTED',
    read: true,
    createdAt: '2026-09-17T11:20:00+07:00',
    actorId: 'user-tuan',
    recipientId: 'user-lan',
  },
  {
    id: 'notif-4',
    title: 'Hồ sơ chờ phê duyệt bước cuối',
    message: 'Tờ trình "TTr-2026/TH-112" đang chờ Tổng Giám đốc phê duyệt hạn mức thực hiện.',
    documentId: 'doc-002',
    documentCode: 'TTr-2026/TH-112',
    type: 'ACTION_REQUIRED',
    read: false,
    createdAt: '2026-09-18T11:45:00+07:00',
    actorId: 'user-nam',
    recipientId: 'user-hai',
    recipientRole: 'DIRECTOR',
    targetStepIndex: 2,
    targetDepartment: 'Ban Giám đốc',
  }
];

export const INITIAL_DEPARTMENTS: DepartmentItem[] = [
  {
    id: 'dept-ktda',
    name: 'Phòng Kỹ thuật & Dự án',
    code: 'KTDA',
    description: 'Chịu trách nhiệm quản lý dự án, giải pháp kỹ thuật, giám sát thi công và nghiệm thu công trình.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'dept-tckt',
    name: 'Phòng Tài chính Kế toán',
    code: 'TCKT',
    description: 'Quản lý dòng tiền, quyết toán thuế, thẩm tra hồ sơ thanh toán và kiểm soát ngân sách chi tiêu.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'dept-bqlda',
    name: 'Ban Quản lý Dự án',
    code: 'BQLDA',
    description: 'Chỉ đạo, điều hành toàn diện công tác quản lý dự án, giám sát chất lượng và tiến độ thi công.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'dept-pcks',
    name: 'Ban Pháp chế & Kiểm soát',
    code: 'PCKS',
    description: 'Thẩm định tính pháp lý hợp đồng kinh tế, quản trị rủi ro và kiểm soát tuân thủ nội bộ.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'dept-bgd',
    name: 'Ban Giám đốc',
    code: 'BGD',
    description: 'Ban điều hành cao nhất công ty, phê duyệt chủ trương, hợp đồng lớn và chiến lược kinh doanh.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'dept-cntt',
    name: 'Phòng CNTT & Hạ tầng',
    code: 'CNTT',
    description: 'Quản trị hệ thống máy chủ, an ninh mạng, phần mềm nghiệp vụ và chuyển đổi số.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'dept-cuvt',
    name: 'Phòng Cung ứng & Vật tư',
    code: 'CUVT',
    description: 'Tìm kiếm nhà cung cấp, đấu thầu mua sắm thiết bị máy móc và quản trị kho vận.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'dept-hcns',
    name: 'Phòng Hành chính Nhân sự',
    code: 'HCNS',
    description: 'Quản trị nhân lực, tuyển dụng, đào tạo, chế độ chính sách và công tác hành chính văn phòng.',
    createdAt: '2026-01-01T08:00:00+07:00'
  }
];

export const INITIAL_JOB_TITLES: JobTitleItem[] = [
  {
    id: 'title-tgd',
    name: 'Tổng Giám đốc',
    code: 'TGD',
    department: 'Ban Giám Đốc',
    defaultRole: 'DIRECTOR',
    description: 'Người đại diện pháp luật, phê duyệt cấp cao nhất mọi hồ sơ, hợp đồng và ngân sách.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'title-ptgd',
    name: 'Phó Tổng Giám đốc',
    code: 'PTGD',
    department: 'Ban Giám Đốc',
    defaultRole: 'DIRECTOR',
    description: 'Phụ trách khối nghiệp vụ chuyên môn theo ủy quyền của Tổng Giám đốc.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'title-ktt',
    name: 'Kế toán trưởng',
    code: 'KTT',
    department: 'Phòng Tài chính - Kế toán',
    defaultRole: 'CHIEF_ACCOUNTANT',
    description: 'Kiểm soát tài chính, duyệt chứng từ thanh toán và thẩm định nguồn vốn.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'title-tbp-pc',
    name: 'Trưởng bộ phận Pháp chế',
    code: 'TBP_PC',
    department: 'Phòng Pháp chế & Kiểm soát',
    defaultRole: 'LEGAL_DEPT',
    description: 'Chịu trách nhiệm thẩm định điều khoản hợp đồng và rủi ro pháp lý.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'title-tb-qlda',
    name: 'Trưởng ban Quản lý Dự án',
    code: 'TB_QLDA',
    department: 'Ban Quản lý Dự án',
    defaultRole: 'BOARD_HEAD',
    description: 'Thẩm quyền phê duyệt cấp Ban cho các dự án, gói thầu và khối lượng thi công.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'title-tp-ktda',
    name: 'Trưởng phòng Kỹ thuật & Dự án',
    code: 'TP_KTDA',
    department: 'Phòng Kỹ thuật & Dự án',
    defaultRole: 'DEPT_HEAD',
    description: 'Duyệt bước 1 về kỹ thuật, khối lượng và tiến độ các gói thầu.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'title-tp-cntt',
    name: 'Trưởng phòng CNTT & Hạ tầng',
    code: 'TP_CNTT',
    department: 'Phòng Công nghệ Thông tin',
    defaultRole: 'DEPT_HEAD',
    description: 'Quản lý và duyệt các đề xuất đầu tư, bảo dưỡng công nghệ thông tin.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'title-cv-da-hd',
    name: 'Chuyên viên Dự án & Hợp đồng',
    code: 'CV_DA_HD',
    department: 'Phòng Kỹ thuật & Dự án',
    defaultRole: 'STAFF',
    description: 'Khởi tạo hồ sơ, soạn thảo hợp đồng kinh tế và theo dõi tiến trình phê duyệt.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'title-cv-kt',
    name: 'Chuyên viên Kế toán',
    code: 'CV_KT',
    department: 'Phòng Tài chính - Kế toán',
    defaultRole: 'STAFF',
    description: 'Đối soát hóa đơn, chuẩn bị hồ sơ tạm ứng và thanh toán.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'title-cv-pc',
    name: 'Chuyên viên Pháp chế',
    code: 'CV_PC',
    department: 'Phòng Pháp chế & Kiểm soát',
    defaultRole: 'STAFF',
    description: 'Soạn thảo và rà soát hồ sơ pháp lý, văn bản ủy quyền.',
    createdAt: '2026-01-01T08:00:00+07:00'
  },
  {
    id: 'title-admin',
    name: 'Quản trị viên Hệ thống',
    code: 'ADMIN',
    department: 'Phòng Công nghệ Thông tin',
    defaultRole: 'ADMIN',
    description: 'Quản trị người dùng, phân quyền chi tiết và cấu hình hệ thống.',
    createdAt: '2026-01-01T08:00:00+07:00'
  }
];

